### ISSUE TITLE
small bug in calculation

### ISSUE THREAD

**Issue by FHilbrunner** [joppiesaus/python-hyt#1]
Hello,

many thanks for the well example!
I think in the combination of the low- and high-byte there is a small mistake.

temperature = 165.0 / 16383.0 * ((reading[2] * 0xFF + (reading[3] & 0xFC)) >> 2) - 40

The factor 0xFF should be 256 for shifting 8 bit.
The resulting error is approx 0.2 °C

Same for humidity.

Best regards

   Falko

**Comment by joppiesaus** [comment]
huh, never noticed this! thank you so much for reporting this issue and explaining it! I just committed the fix. have a great day!
